[features]
seeds = false
skip-lint = false
[programs.localnet]
myepicproject = "HVKwNxecPnQivyPfgUf54F1veJwtVkXzC9agdXMmxtgG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/douglaspoma/.config/solana/id.json"

[scripts]
# test = "node tests/myepicproject.js"
test = "yarn run mocha -t 1000000 tests/"
